---
- name: Copy shell script rook_ceph.sh to target
  copy:
    src: rook_ceph.sh 
    dest: /tmp/rook_ceph.sh  
    mode: '0755'    # This ensures the script is executable

- name: Install rook_ceph on cluster
  shell: timeout 600s /tmp/rook_ceph.sh > /tmp/rook_ceph.log 
  register: rook_ceph
  ignore_errors: True 

- name: gather rook-ceph logs 
  shell: cat /tmp/rook_ceph.log 
  register: rook_ceph_output
  ignore_errors: True
  no_log: True

- name: print rook_ceph logs
  debug:
    var: rook_ceph_output.stdout_lines
  when: rook_ceph_output is defined and rook_ceph_output.stdout_lines is defined

- name: fail if rook-ceph installation timed-out or failed
  fail:
    msg: "Unable to complete rook ceph installation in 10 mins."
  when: rook_ceph.failed
